### ISSUE TITLE
Changing maxItems value does not makes effect

### ISSUE THREAD

**Issue by elreymon** [laster04/Idealista-scraper#1]
In the web I change de "maxItems" value but the actor does not seem to be aware of the chage.
At the first run I´ve configured a value of 35 max items. Now it does not matter whatever value I set, it allways do 31 handles. Only retrives 31 results.

Update: It seems the actor only scrapes the URL of the first page that has 30 results. It does not keeps seeking next pages. Maybe thst´s the reason why it only scrapes 31 items.

**Comment by elreymon** [comment]
Lower limit than 31, example: 3 doesn´t either works:

{
  "district": "Fuencarral, Madrid",
  "maxItems": 3,
  "proxy": {
    "useApifyProxy": true,
    "apifyProxyGroups": [
      "RESIDENTIAL"
    ],
    "apifyProxyCountry": "ES"
  }
}

**Comment by laster04** [comment]
@elreymon Hello i fixed it try version 0.0.7.

**Comment by elreymon** [comment]
Tryed and OK. Thanks.
