### ISSUE TITLE
Add "Rooms" to JSON

### ISSUE THREAD

**Issue by sergiolindolfoferreira** [laster04/Idealista-scraper#5]
Hi laster04,

It would be possible in JSON to add the "rooms" field this data is fundamental for a Property, just as we have the "baths", create at the same level as JSON.

If it doesn't exist, we have to be looking for the "rooms" in the characteristics.

I would really appreciate it if you could do this.

{
  "url": "https://www.idealista.com/inmueble/102897038/",
  "listingUrl": "https://www.idealista.com/venta-viviendas/madrid-madrid/pagina-2.htm",
  "title": "Piso en venta en calle del Desengaño",
  "id": "102897038",
  "price": "675000",

  **"rooms" : ""**,

  "baths": "1",
  "description": "Gilmar presenta para sus clientes de la zona centro de la capital, una magnífica oportunidad de adquirir la vivienda de tus sueños.Te presentamos una oportunidad única en la zona de Sol. Se trata de un acogedor piso en la planta cuarta, exterior y luminoso, con dos dormitorios y un baño.",
  "address": "Malasaña-Universidad, Madrid",
  "typology": "Pisos",
  "photos": [
    "https://img3.idealista.com/blur/WEB_DETAIL/0/id.pro.es.image.master/81/47/e2/1171811252.jpg",
    "https://img3.idealista.com/blur/WEB_DETAIL/0/id.pro.es.image.master/36/0b/2b/1171811236.jpg",
    "https://img3.idealista.com/blur/WEB_DETAIL/0/id.pro.es.image.master/f9/19/aa/1171811237.jpg",
    "https://img3.idealista.com/blur/WEB_DETAIL/0/id.pro.es.image.master/18/86/45/1171811232.jpg",
    "https://img3.idealista.com/blur/WEB_DETAIL/0/id.pro.es.image.master/ce/47/e6/1171811217.jpg",
    "https://img3.idealista.com/blur/WEB_DETAIL/0/id.pro.es.image.master/35/10/17/1184017143.jpg"
  ],
  "video": "https://st3v.idealista.com/2e/69/47/hd_1172345780.mp4",
  "breadcrumbs": [
    "Madrid provincia",
    "Madrid"
  ],
  "features": [
    "107 m² construidos",
    "2 habitaciones",
    "1 baño",
    "Balcón",
    "Segunda mano/buen estado",
    "Armarios empotrados",
    "Trastero",
    "Orientación sur, este",
    "Construido en 1900",
    "Calefacción individual",
    "Planta 4ª exterior",
    "Con ascensor",
    "Aire acondicionado",
    "Consumo:",
    "Emisiones:"
  ],
  "tags": [],
  "hideAddress": true,
  "advertiserProfessionalName": "Gilmar Centro",
  "advertiserName": "Gilmar Centro",
  "status": "online",
  "latitude": "40.4207255",
  "longitude": "-3.7030809",
  "3dtour": "https://my.matterport.com/show/?m=ma27yuXyVBf",
  "listingUpdate": "Anuncio actualizado el 24 de noviembre",
  "sqft": 107,
  "consumo:": "E",
  "emisiones:": "E",
  "ubicationAddress": "Calle del Desengaño"
},

**Comment by laster04** [comment]
Hello, i try it in new version. Can you check it?

**Comment by sergiolindolfoferreira** [comment]
YEEESSSSS.
That's it, thank you very much.
