### ISSUE TITLE
Scraping sold properties

### ISSUE THREAD

**Issue by xDelivered-Patrick** [laster04/Idealista-scraper#6]
Hello! Your docs mention about scraping sold properties, but I'm not sure exactly how to achieve that. 
In fact, I don't see sold properties as an option in Idealista UX - am I missing something?
Scraping the sold properties would be fantastic if possible.

**Comment by laster04** [comment]
Hello, sorry for mystification but right now Idealista can't scrape sold properties. It can scrape sold property access throught the current link to detail. So when you have list of detail links the scraper should inform you that the property is already sold. Once again sorry for wrong description.
